---
- name: Check if yaourt is installed
  shell: pacman -Q yaourt
  ignore_errors: yes
  register: is_yaourt_installed

- name: "Add [archlinux.fr] repository to pacman"
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
  when: is_yaourt_installed.rc != 0

- name: "Install yaourt"
  pacman:
    update_cache: yes
    name: "yaourt"
    state: "present"
  when: is_yaourt_installed.rc != 0

- name: "Remove [archlinux.fr] repository"
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "absent"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
  when: is_yaourt_installed.rc != 0
