---
- name: Decrypt files
  become: false
  hosts: target
  gather_facts: false
  vars_files:
    - vars/vault.yml
  tasks:
    - name: Decrypt vault files
      ansible.builtin.command:
        cmd: ansible-vault decrypt {{ files | join(' ') }}
      changed_when: true
