---
- name: Encrypt files
  become: false
  hosts: target
  gather_facts: false
  vars_files:
    - vars/vault.yml
  tasks:
    - name: Encrypt vault files
      ansible.builtin.command:
        cmd: ansible-vault encrypt {{ files | join(' ') }}
      changed_when: true
