---

- name: Check if cbatticon is installed
  command: dpkg-query -W cbatticon
  register: cbatticon_check_deb
  failed_when: cbatticon_check_deb.rc > 1
  changed_when: cbatticon_check_deb.rc == 1

- name: Download cbatticon
  get_url:
    url="http://ftp.debian.org/debian/pool/main/c/cbatticon/cbatticon_1.6.8-1_amd64.deb"
    dest="/tmp/cbatticon.deb"
  when: cbatticon_check_deb.rc == 1

- name: Install cbattiocn
  apt: deb="/tmp/cbatticon.deb"
  become: yes
  when: cbatticon_check_deb.rc == 1
