---

- name: Download keyring for i3
  shell: /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb /tmp/keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416

- name: dpkg keyring of i3
  become: yes
  shell: dpkg -i /tmp/keyring.deb

- name: Install vm packages
  command: apt install -y "{{ item }}"
  become: yes
  with_items:
      "{{ vm_packages[configs.vm] }}"

