---

- name: Download keyring for i3
  shell: /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2020.02.03_all.deb /tmp/keyring.deb SHA256:c5dd35231930e3c8d6a9d9539c846023fe1a08e4b073ef0d2833acd815d80d48

- name: dpkg keyring of i3
  become: yes
  shell: dpkg -i /tmp/keyring.deb

- name: Install vm packages
  command: apt install -y "{{ item }}"
  become: yes
  with_items:
      "{{ vm_packages[configs.vm] }}"

