---

- name: Add PPAs
  apt_repository:
    repo: "{{ item }}"
  with_items:
      "{{ repo_ppa }}"
  ignore_errors: yes

- name: Add Debs
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
      "{{ repo_deb }}"

- name: Add an Apt signing key
  apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
  with_items:
      "{{ keys }}"

- name: Update
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Install Apt packages
  command: apt install -y "{{ item }}"
  become: yes
  with_items:
      "{{ p }}"

- name: Install Pip packages
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
      "{{ packages_pip }}"

- name: Remove PPAs
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
      "{{ repo_ppa }}"
  ignore_errors: yes

- name: Remove Debs
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items:
      "{{ repo_deb }}"

- name: Add an Apt signing key
  apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
    state: absent
  with_items:
      "{{ keys }}"

- name: Cloning oh-my-zsh
  become: no
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
    update=yes

- name: Install tmux plugin manager
  git:
    repo=https://github.com/tmux-plugins/tpm
    dest=~/.tmux/plugins/tpm
    update=yes
  become: no

- name: Download and Unarchive oblogout
  become: no
  unarchive:
    src: https://github.com/burakkose/oblogout-fork/archive/v1.0.zip
    dest: /tmp
    remote_src: yes

- name: Install oblogout
  shell: cd /tmp/oblogout-fork-1.0/ && ./setup.py install

- name: Unarchive URxvt Perls
  become: no
  unarchive:
    src: https://github.com/muennich/urxvt-perls/archive/2.2.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move Urxvt Perls
  shell: mv /tmp/urxvt-perls-2.2/* /usr/lib/urxvt/perl/
