---

- name: Install Polybar dependencies
  command: apt install -y "{{ item }}"
  become: yes
  with_items:
      "{{ polybar_deps }}"

- name: Clone polybar project
  become: no
  git:
    repo=https://github.com/jaagr/polybar.git
    dest=/tmp/polybar
    update=yes

- name: Clone Siji font
  become: no
  git:
    repo=https://github.com/stark/siji.git
    dest=/tmp/siji
    update=yes

- name: Clone Font Awesome
  become: no
  git:
    repo=https://github.com/FortAwesome/Font-Awesome
    dest=/tmp/font-awesome
    update=yes

- name: Rename 70-no-bitmaps if exists
  become: yes
  shell: mv /etc/fonts/conf.d/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf.old
  ignore_errors: yes

- name: Install Siji font
  shell: cd /tmp/siji && ./install.sh

- name: Install font awesome (ttf)
  shell: cp /tmp/font-awesome/webfonts/*.ttf ~/.local/share/fonts/

- name: Install font awesome (otfs)
  shell: cp /tmp/font-awesome/otfs/*.otf ~/.local/share/fonts/

- name: Refresh font cache
  become: yes
  shell: fc-cache

- name: Build polybar
  shell: cd /tmp/polybar && ./build.sh --all-features

