---

- name: Install Polybar dependencies
  command: apt install -y "{{ item }}"
  become: yes
  with_items:
      "{{ polybar_deps }}"

- name: Clone polybar project
  become: no
  git:
    repo=https://github.com/jaagr/polybar.git
    dest=/tmp/polybar
    update=yes

- name: Clone xcb-util-xrm project
  become: no
  git:
    repo=https://github.com/Airblader/xcb-util-xrm
    dest=/tmp/xcb-util-xrm
    update=yes

- name: Build xcb-util-xrm project
  become: yes
  shell: cd /tmp/xcb-util-xrm && git submodule update --init && ./autogen.sh --prefix=/usr && make && make install

- name: Build polybar
  shell: cd /tmp/polybar && ./build.sh --all-features
