---
- name: Upgrade the system
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  command: yaourt -S "{{ item }}" --noconfirm --needed
  ignore_errors: yes
  with_items:
      "{{ packages }}"
