---
- name: Upgrade the system
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install common packages
  command: trizen -S "{{ item }}" --noconfirm --needed
  become: no
  with_items:
      "{{ packages }}"

- name: Install wm packages
  command: trizen -S "{{ item }}" --noconfirm --needed
  become: no
  with_items:
      "{{ vm_packages[configs.vm] }}"

- name: Link oh my zsh
  ignore_errors: yes
  file:
    src: '/usr/share/oh-my-zsh'
    dest: '~/.oh-my-zsh'
    state: link
    force: yes
  when: '"oh-my-zsh-git" in packages'

- name: Link browser
  file:
    src: '/usr/bin/brave'
    dest: '/usr/bin/browser'
    state: link
    force: yes
