---
- name: Upgrade the system
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install common packages
  command: trizen -S "{{ item }}" --noconfirm --needed
  become: no
  with_items:
      "{{ packages }}"

- name: Install wm packages
  command: trizen -S "{{ item }}" --noconfirm --needed
  become: no
  with_items:
      "{{ vm_packages[configs.vm] }}"

- name: Link browser
  file:
    src: '/usr/bin/firefox'
    dest: '/usr/bin/browser'
    state: link
    force: yes

- name: Link editor
  file:
    src: '/usr/bin//featherpad'
    dest: '/usr/bin/editor'
    state: link
    force: yes

- name: Link copy
  file:
    src: '/usr/bin//wl-copy'
    dest: '/usr/bin/copy'
    state: link
    force: yes
