---
- name: Upgrade the system
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  command: trizen -S "{{ item }}" --noconfirm --needed
  become: no
  with_items:
      "{{ packages }}"

- name: Link oh my zsh
  ignore_errors: yes
  file:
    src: '/usr/share/oh-my-zsh'
    dest: '~/.oh-my-zsh'
    state: link
    force: yes
  when: '"oh-my-zsh-git" in packages'
