---
packages:
  - arandr
  - arc-gtk-theme
  - atom-editor-bin
  - base
  - base-devel
  - cbatticon
  - clojure
  - compton
  - conky
  - docker
  - evince
  - feh
  - firefox-developer-edition
  - fpp-git
  - galculator
  - google-chrome
  - gsimplecal
  - gtk2
  - gtk3
  - htop
  - httpie
  - i3lock-blur
  - imagemagick
  - intellij-idea-ultimate-edition
  - jdk9-openjdk
  - jq
  - leafpad
  - libreoffice-fresh
  - lxappearance
  - lxinput
  - lxmenu-data
  - neofetch
  - network-manager-applet
  - networkmanager-openvpn
  - obconf
  - obkey
  - oblogout
  - obmenu
  - oh-my-zsh-git
  - openbox
  - openbox-menu
  - openssh
  - papirus-icon-theme
  - pcmanfm
  - powerline
  - powerline-fonts
  - ranger
  - rbenv
  - redshift
  - rofi
  - rxvt-unicode
  - sbt
  - scala
  - scrot
  - slack-desktop
  - spotify
  - telegram-desktop-bin
  - the_silver_searcher
  - thefuck
  - thunderbird
  - tig
  - tint2
  - tmux
  - tpm
  - transmission-gtk
  - ttf-inconsolata
  - ttf-ms-fonts
  - unrar
  - urxvt-perls
  - vlc
  - volumeicon
  - wget
  - wmctrl
  - xarchiver
  - xclip
  - xorg
  - xorg-xinit
  - xorg-xclipboard

