- command: 'ls {{ configs.dotfile_repo_path }}/data/{{ dir }}'
  register: dir_out

- file:
    path: '~/.{{ dir }}'
    state: directory

- file:
    src: '{{ configs.dotfile_repo_path }}/data/{{ dir }}/{{ item }}'
    dest: '~/.{{ dir }}/{{ item }}'
    state: link
    force: yes
  with_items:
    "{{ dir_out.stdout_lines }}"