---
- name: Define timestamp
  set_fact:
    current: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

- name: Define variables
  set_fact:
    backup_dir: "{{ configs.dotfile_backup_path }}/{{ current }}"

- name: Create backup directory
  file:
    path: "{{ backup_dir }}"
    state: directory

- name: Copy existing dotfiles to backup directory (Directly)
  ignore_errors: true
  command: cp -Lr ~/.{{ item }} {{ backup_dir }}/{{ item }}
  with_items:
    "{{ directly }}"

- name: Copy existing dotfiles to backup directory (Partially)
  ignore_errors: true
  include_role:
    name: dotfile
    tasks_from: backup-partially
  with_items:
    "{{ partially }}"
  loop_control:
    loop_var: dir

- name: Apply files directly (Directly)
  file:
    src: '{{ configs.dotfile_repo_path }}/data/{{ item }}'
    dest: '~/.{{ item }}'
    state: link
    force: yes
  with_items:
    "{{ directly }}"

- name: Apply files partially (Partially)
  include_role:
    name: dotfile
    tasks_from: apply-partially
  with_items:
    "{{ partially }}"
  loop_control:
    loop_var: dir

- git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: ~/.tmux/plugins/tpm
    clone: yes

- name: Apply obtheme
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  with_items:
    - {src: '{{ configs.dotfile_repo_path }}/data/themes/obtheme', dest: '/usr/share/themes/'}
    - {src: '{{ configs.dotfile_repo_path }}/data/oblogout.conf', dest: '/etc/oblogout.conf'}
