---
- set_fact:
    current: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
    backup_dir: "{{configs.dotfile_backup_path}}/{{current}}"

- name: Create backup directory
  file:
      path: "{{backup_dir}}"
      state: directory

- name: Copy existing dotfiles to backup directory
  shell: cp -Lr ~/.{{ item }} ~/{{backup_dir}}/{{item}}
  with_items:
      "{{ files }}"

- name: Clone tmux plugin manager
  shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ignore_errors: yes

- name: Apply new dotfiles
  file:
      src: '{{configs.dotfile_repo_path}}/data/{{ item }}'
      dest: '~/.{{ item }}'
      state: link
  with_items:
      "{{ files }}"

- name: Apply obtheme
  become: yes
  file:
      src: "{{ item[0] }}"
      dest: "{{ item[1] }}"
      state: link
  with_items:
      - ['~/.themes/obtheme', '/usr/share/themes/obtheme']
      - ['{{configs.dotfile_repo_path}}//data/oblogout.conf', '/etc/oblogout.conf']
